name: daily_vibes_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  provider: ^6.1.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^18.0.0
  workmanager: ^0.5.2
  # web: ^1.1.0  # Only for web builds

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/screens/icon.png"
  web:
    generate: true
    image_path: "lib/screens/icon.png"
    background_color: "#FF6B9D"
    theme_color: "#FF6B9D"
  windows:
    generate: true
    image_path: "lib/screens/icon.png"
    icon_size: 48
